### PR TITLE
Fix - Diff Editor background colours

### PR DESCRIPTION
**Pull request by lautit**
Changed the bright orange background for diff lines in the dark Catalina and Civic themes because... It hurts!

**Before:**
image

**After:**
image

### CODE REVIEW

**Comment by prometheas** [comment]
This PR is 25 days old… combined with how long ago the last code pushes were made, I'm wondering whether it's worth my making any PRs myself (I'm entertaining the idea of integrating the [node-dark-mode](https://github.com/sindresorhus/node-dark-mode) package to align light/dark mode in VS Code with the system's setting via the package's `isDark()` call.

I don't mean this inquiry in any sort of passive-aggressive manner, mind you—I've certainly been slow to respond on a few interactions on my own Github projects 😅 life happens! But if it's no longer maintained, I'll consider alternatives.

**Comment by prometheas** [comment]
This PR is 25 days old… combined with how long ago the last code pushes were made, I'm wondering whether it's worth my making any PRs myself (I'm entertaining the idea of integrating the [node-dark-mode](https://github.com/sindresorhus/node-dark-mode) package to align light/dark mode in VS Code with the system's setting via .

I don't mean this inquiry in any sort of passive-aggressive manner, mind you—I've certainly been slow to respond on a few interactions on my own Github projects 😅 life happens! But if it's no longer maintained, I'll consider alternatives.

**Comment by prometheas** [comment]
Upon a bit of further hunting, I've found that [Auto Dark Mode extension](https://github.com/LinusU/vscode-auto-dark-mode) suits my needs perfectly. Please disregard my inquiry 😉

**Comment by davidbwaters** [comment]
Sorry I haven't shown this project any love in a while. I have a few issues I haven't gotten a chance to fix and tweaks to make. PRs and suggestions are welcome and I will do better keeping up with them. Thanks for the fix!

**Pull request merged**
